version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: vizinhelp-bd
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:20.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/vizinhelp-bd
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - 9090:8080
    command:
      - start-dev
    volumes:
      - keycloakdata:/opt/jboss/keycloak/standalone/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
      
volumes:
  postgresdata:  # Define o volume para dados do PostgreSQL
  keycloakdata:  # Define o volume para dados do Keycloak