version: '3.8'

services:
  postgres:
    image: 'postgres:15'
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: vizinhelp-bd
    ports:
      - '5433:5432'
    volumes:
      - './docker_data/postgres:/var/lib/postgresql/data'
  keycloak:
    image: 'quay.io/keycloak/keycloak:20.0'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://vizinhelp-bd.crkq2o86ubrq.us-east-1.rds.amazonaws.com:5432/vizinhelp-bd
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: vizinhelp
    ports:
      - '9090:8080'
    command:
      - start-dev
    volumes:
      - './docker_data/keycloak:/data'
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
