pipeline {
    agent any
    tools {nodejs "Node"}
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main',
                    url:'https://github.com/vcosmusjoao/vizinhelp.git'
            }
        }
        
        stage('Install Dependencies') {
            steps {
                bat 'npm install'
            }
        }
        
        stage('Build') {
            steps {
                bat 'npm run build'
            }
        }
        
        stage('Test') {
            steps {
                bat 'npm test'
            }
        }
        
    }
}
