name: Deploy Remotely
on:
  push:
    branches: [ main ]
 
jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest
    steps:
    - name: Change Directory to Frontend
      run: cd frontend   # Substitua 'frontend' pelo nome correto do diretório do seu projeto Angular
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Use Node.js 20.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - run: npm install
    - run: npm run build --prod
    - name: Transfer Build Folder on EC2 Instance
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "dist/"  # O diretório de construção do Angular geralmente é 'dist'
        TARGET: ${{ secrets.DEPLOY_TARGET }}
